import { miniaturesArray} from './data.js';
import { createMiniImageList } from './creat-miniatures.js';
import { viewBigPicture } from './big-picture.js';
import { loadYourPicture } from './form.js';
import { controlScaleImage } from './control-scale-image.js';
import  { effectForImageChange } from './effects.js';
createMiniImageList(miniaturesArray);
viewBigPicture();
loadYourPicture();
controlScaleImage();
effectForImageChange();
